
services:
  drone-norte:
    build:
      context: .
      dockerfile: Dockerfile
    image: climate-data:latest
    environment:
      - DRONE_NAME=Norte
      - DRONE_PORT=8081
      - DRONE_DELIMITER=-
      - DRONE_START=
      - DRONE_END=
    ports:
      - "8081:8080"

  drone-sul:
    build:
      context: .
      dockerfile: Dockerfile
    image: climate-data:latest
    environment:
      - DRONE_NAME=Sul
      - DRONE_PORT=8082
      - DRONE_DELIMITER=;
      - DRONE_START=(
      - DRONE_END=)
    ports:
      - "8082:8080"

  drone-leste:
    build:
      context: .
      dockerfile: Dockerfile
    image: climate-data:latest
    environment:
      - DRONE_NAME=Leste
      - DRONE_PORT=8083
      - DRONE_DELIMITER=,
      - DRONE_START={
      - DRONE_END=}
    ports:
      - "8083:8080"

  drone-oeste:
    build:
      context: .
      dockerfile: Dockerfile
    image: climate-data:latest
    environment:
      - DRONE_NAME=Oeste
      - DRONE_PORT=8084
      - DRONE_DELIMITER=#
      - DRONE_START=
      - DRONE_END=
    ports:
      - "8084:8080"
